service:
  name: aws-nodejs-typescript-demo

provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: dist/handler.hello
    events:
      - http:
          method: get
          path: hello
